### ISSUE TITLE
Unknown action type move-to-center-x

### ISSUE THREAD

**Issue by mgualti** [pantor/speedfolding#1]
Hello,

I tried training the bimama network with the data set from https://pantor.github.io/speedfolding/. I get the following error:

```
Traceback (most recent call last):ng: 2027.001, pnh: 3384.1908509580
  File "train.py", line 114, in <module>```
    trainer.fit(model, epochs=100)
  File "train.py", line 48, in fit
    for i_batch, batch in enumerate(self.train_data):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/Projects/speedfolding_fork/learning/bimama/dataset.py", line 129, in __getitem__
    assert action['type'] in self.primitive_classes, "Unknown action type, move-to-center-x."
AssertionError: Unknown action type, move-to-center-x."
AssertionError: Unknown action type
```

Is it safe to just ignore the unknown actions?

**Comment by zcswdt** [comment]
Have you solved this problem？
